## Numpy Array Operation

In [3]:
import numpy as np
arr = np.array([0,1,2,3,4,5,6,7,8,9,10])

print("Basic Slicing :", arr[2: 7])      # Index 2 to 6 (7 excluded) 
print("With Step :", arr[1:8:2])         # Index 1 to 7 with step of 2
print("Negative Indexing", arr[-2])      # Second last element

Basic Slicing : [2 3 4 5 6]
With Step : [1 3 5 7]
Negative Indexing 9


In [4]:
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print("Specific Element :", arr_2d[0, 2])       # Element at row 0, column 2
print("Entire Row :", arr_2d[1])                # Entire second row (index 1)
print("Entire Column :", arr_2d[:,2])           # Entire third column (index 2)

Specific Element : 3
Entire Row : [4 5 6]
Entire Column : [3 6 9]


## Sorting


In [5]:
unsorted = np.array([2,5,1,8,3,1,9,5,2,7,6,4,2])
print("Sorted Array :", np.sort(unsorted))

Sorted Array : [1 1 2 2 2 3 4 5 5 6 7 8 9]


In [6]:
unsorted_2d_array = np.array([[7,1], [4,1], [9,3]])
print("Sorted 2d Array Default by Row :", np.sort(unsorted_2d_array))
print("Sorted 2d Array by Row :", np.sort(unsorted_2d_array, axis=1))      # (axis=1 means row-wise)
print("Sorted 2d Array by Column :", np.sort(unsorted_2d_array, axis=0))   # Sorting each column (axis=0 means column-wise)

Sorted 2d Array Default by Row : [[1 7]
 [1 4]
 [3 9]]
Sorted 2d Array by Row : [[1 7]
 [1 4]
 [3 9]]
Sorted 2d Array by Column : [[4 1]
 [7 1]
 [9 3]]


## Filter


In [7]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_num = numbers[numbers % 2 == 0]
print("Even Numbers :", even_num)

Even Numbers : [ 2  4  6  8 10]


## Filter with Mask

### A mask in NumPy is a boolean array used for:

1. Filtering data
2. Selecting specific elements based on a condition
3. Modifying specific elements conditionally
4. Performing computations on selected elements only

In [8]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
mask = numbers > 5
print("numbers greater than 5 :", numbers[mask])

numbers greater than 5 : [ 6  7  8  9 10]


### Fancy indexing vs np.where()

In [9]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
indices = [0,2,4]    # Direct indexing using a list of specific indices
print(numbers[indices])

where_result = np.where(numbers > 5)    # np.where returns the indices where the condition is True
print(where_result)                     # Returns tuple of indices where numbers > 5

# Using the indices from where_result to access numbers > 5
print("NP where ", numbers[where_result])    


[1 3 5]
(array([5, 6, 7, 8, 9]),)
NP where  [ 6  7  8  9 10]


In [10]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
condition_arr = np.where(numbers > 5, numbers*2, numbers)
print(condition_arr)

[ 1  2  3  4  5 12 14 16 18 20]


## Adding and Removing Data

In [15]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
combined = np.concatenate((arr1, arr2))
print(combined)

[1 2 3 4 5 6]


## Array Compatibility

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9,10])
print("Compatibility shapes", a.shape == b.shape)     # Check if the shape (size/dimensions) of array 'a' and 'b' are the same
print("compatibility shapes", b.shape == c.shape)     # Check if the shape of 'b' and 'c' are the same

Compatibility shapes True
compatibility shapes False


In [ ]:
original_row = np.array([[1,2], [3,4]])
new_row = np.array([5,6])

# np.vstack() is used to stack arrays vertically (row-wise).
# It combines multiple arrays by adding them as new rows, provided that the number of columns match.
with_new_row = np.vstack((original_row, new_row))    # Stack the new_row vertically to the original_row
print("Original Row \n", original_row)
print("With New Row \n", with_new_row)

Original Row 
 [[1 2]
 [3 4]]
With New Row 
 [[1 2]
 [3 4]
 [5 6]]


In [ ]:
original_row = np.array([[1,2], [3,4]])
new_col = np.array([[5], [6]])

#  np.hstack() is used to horizontally stack (join side by side) multiple arrays. 
# It concatenates along columns, so the number of rows must be the same in all arrays.
with_new_col = np.hstack((original_row, new_col))    # Horizontally stack 'new_col' to the right of 'original_row'
print(with_new_col)

[[1 2 5]
 [3 4 6]]


In [ ]:
arr = np.array([1,2,3,4,5])
deletion = np.delete(arr, 2)     # Delete element at index 2 (3rd element, which is 3)
print("Array after Deletion :", deletion)

Array after Deletion : [1 2 4 5]
