Learn abount numpy


In [5]:
import numpy as np

Creating array from list

In [6]:
arr_1d = np.array([1,2])
print("1D Array :", arr_1d)

1D Array : [1 2]


In [7]:
arr_1d = np.array([1,2,3])
print("1D Array", arr_1d)
print(arr_1d.dtype)
print(arr_1d.shape)
print(arr_1d.size)

1D Array [1 2 3]
int64
(3,)
3


In [8]:
arr_2d = np.array([[1,2,3], [4,5,6]])
print("2D ARRAY :", arr_2d)

2D ARRAY : [[1 2 3]
 [4 5 6]]


In [9]:
arr_2d = np.array([[1,2,3,4], [5,6,7,8]])
print("2D Array :", arr_2d)
print(arr_2d.dtype)
print(arr_2d.shape)
print(arr_2d.size)

2D Array : [[1 2 3 4]
 [5 6 7 8]]
int64
(2, 4)
8


List vs numpy Array

In [10]:
py_list = [1,2,3]
print("python list multiplication", py_list * 2)

python list multiplication [1, 2, 3, 1, 2, 3]


In [11]:
py_arr = np.array([1,2,3])   # Elements wise multiplication
print("python array multiplication", py_arr * 2)

python array multiplication [2 4 6]


Measuring Execution Time of List Comprehension in Python

In [12]:
# Importing time module to measure execution time
import time

# Record the start time
start = time.time()

# Creating a Python list with numbers multiplied by 2 from 0 to 999999
py_list = [i * 2 for i in range(1000000)]

# Calculating the total time taken for the above operation
print("\n List operation time: ", time.time() - start)



 List operation time:  0.19475317001342773


Measuring Execution Time of NumPy Array Operation

In [13]:
import time             # For measuring execution time
import numpy as np      # For numerical operations

# Record the start time
start = time.time()

# Create a NumPy array with numbers from 0 to 999999 and multiply each by 2
py_arr = np.arange(1000000) * 2

# Print the time taken to perform the NumPy operation
print("\nNumpy operation time: ", time.time() - start)



Numpy operation time:  0.01196742057800293


Creating Array from Scratch

In [14]:
zeros = np.zeros((3,4))
print("zeros array \n", zeros)

zeros array 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [15]:
ones = np.ones((3,4))
print("ones array \n", ones)

ones array 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [16]:
full = np.full((3,4), 7)
print("full array \n", full)

full array 
 [[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [19]:
random = np.random.random((2,3))
print("random array : \n", random)

random array : 
 [[0.20903626 0.16567161 0.48425373]
 [0.82196893 0.20639216 0.68553487]]


In [22]:
sequence = np.arange(0, 11, 2)
print("sequence array \n", sequence)

sequence array 
 [ 0  2  4  6  8 10]
