In [3]:
import numpy as np
arr = np.array([[10,20,30],
                [40,50,60]])             # Creating a 2D NumPy array (2 rows, 3 columns)
print("Shape :", arr.shape)              # Shape shows the number of rows and columns
print("Dimension :", arr.ndim)           # ndim tells us if the array is 1D, 2D, 3D, etc
print("Size :", arr.size)                # Size is simply the count of all elements in the array (2*3=6)
print("DType :", arr.dtype)              # dtype shows the data type of each element in the array

Shape : (2, 3)
Dimension : 2
Size : 6
DType : int64


Array Reshaping

In [ ]:
arr = np.arange(12)      # Create a 1D array with values from 0 to 11 (12 elements)
print("Original array ", arr)

reshaped = arr.reshape((3,4))       # Reshape the 1D array into a 3x4 2D array
print("Reshaped array \n", reshaped)

# Meaning of Flatten in NumPy
# Flattening means converting a multi-dimensional array into a 1D array.
# It collapses all dimensions into a single linear sequence.

flattened = reshaped.flatten()        # Flatten the 2D array back to 1D array
print("flattened array ", flattened)


# ravel() converts a multi-dimensional array to 1D, just like flatten(), but:
# ravel() returns a view of the original array when possible (no data copying).
# flatten() always returns a copy.

raveled = reshaped.ravel()
print("raveled array ", raveled)

transpose = reshaped.T        #  .T returns the transpose of the array, i.e., it swaps rows and columns.
print("transposed array \n", transpose)

Original array  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
flattened array  [ 0  1  2  3  4  5  6  7  8  9 10 11]
raveled array  [ 0  1  2  3  4  5  6  7  8  9 10 11]
transposed array 
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
