###  Generate Random Number

In [3]:
from numpy import random

#   Generate a random integer from 0 to 100:

x = random.randint(100)
print(x)


25


In [5]:
#   Generate a random float from 0 to 1:

x = random.rand()
print(x)

0.9565436388716785


In [9]:
#   Generate a 1-D array containing 5 random integers from 0 to 100:

x = random.randint(100, size = (5))
print(x)

[89 37 47 56  4]


In [13]:
#   Generate a 2-D array with 3 rows, each row containing 5 random integers from 0 to 100:

x = random.randint(100, size = (2,3))
print(x)

[[32 47 11]
 [59 22 65]]


In [14]:
#   Generate a 1-D array containing 5 random floats:


x = random.rand(5)
print(x)

[0.99128839 0.60421598 0.76102374 0.48266983 0.71441732]


In [15]:
#   Generate a 2-D array with 3 rows, each row containing 5 random numbers:

x = random.rand(3, 5)
print(x)

[[0.27202253 0.28609911 0.65590658 0.66341196 0.56738843]
 [0.45595128 0.92321328 0.85398703 0.06169249 0.33793039]
 [0.20519101 0.20307872 0.93518369 0.09329878 0.74016864]]


In [17]:
#   Return one of the values in an array:
#   The choice() method allows you to generate a random value based on an array of values.
#   The choice() method takes an array as a parameter and randomly returns one of the values.

x = random.choice([10, 20, 30, 40])
print(x)

20


In [20]:
#   Generate a 2-D array that consists of the values in the array parameter (10, 20, 30, and 40):

x = random.choice([10, 20, 30, 40], size = (3,5))
print(x)

[[20 20 20 30 30]
 [10 10 30 20 20]
 [40 20 40 40 20]]


# Random Data Distribution

In [26]:
# Generate a 1-D array containing 100 values, where each value has to be 3, 5, 7 or 9.
# The probability for the value to be 3 is set to be 0.1 (0.1 → 10% chance)
# The probability for the value to be 5 is set to be 0.3 (0.3 → 30% chance)
# The probability for the value to be 7 is set to be 0.6 (0.6 → 60% chance)
# The probability for the value to be 9 is set to be 0   (0.0 → 0% chance (kabhi nhi aayega))

x = random.choice([3,5,7,9], p=[0.1, 0.3, 0.6, 0.0], size=(100))
print(x)

[5 7 5 5 5 7 7 7 7 7 7 5 5 7 7 7 7 5 7 5 7 7 7 5 7 7 7 5 7 7 3 7 7 3 3 7 5
 7 7 7 7 3 3 3 7 7 7 7 7 5 7 7 7 7 7 7 5 7 7 5 7 5 5 3 7 5 7 3 7 5 3 7 5 5
 7 3 5 7 7 7 7 5 5 5 3 5 5 7 5 5 5 5 7 3 5 7 7 7 7 7]


In [29]:
x = random.choice([3,5,7,9], p=[0.1,0.3,0.6,0.0], size=(3,5))
print(x)

[[5 7 7 7 5]
 [7 7 7 3 5]
 [7 7 7 5 7]]
