In [12]:
import numpy as np
# import matplotlib.pyplot as plt

In [ ]:
array1 = np.array([[1,2,3],[4,5,6]])    # Create a 2D numpy array
array2 = np.random.random((3,3))        # Create a 3x3 numpy array with random float values between 0 and 1

In [16]:
#  np.save() is used to save a NumPy array to a file on disk, so that you can reuse or reload it later without regenerating or recalculating the data.

np.save('array1.npy', array1)    # Save array1 to a binary .npy file
np.save('array2.npy', array2)    # Save array2 to a binary .npy file

In [18]:
#  np.load() is used to load (read) a saved NumPy array from a .npy or .npz file back into memory.
# Suppose you saved a large array using np.save(). Instead of recreating the data every time, you can quickly load it with np.load().
# Saves time & computation.

loaded_array1 = np.load('array1.npy')     # Load the saved array1 from the .npy file
print(loaded_array1)

loaded_array2 = np.load('array2.npy')     # Load the saved array2 from the .npy file
print(loaded_array2)

[[1 2 3]
 [4 5 6]]
[[0.72679049 0.27714165 0.68334995]
 [0.06573    0.26156655 0.32785216]
 [0.26507003 0.02510452 0.03872655]]
