In [2]:
import numpy as np

Vector


In [4]:
vector = np.array([1,2,3])
print("vector \n", vector)

vector 
 [1 2 3]


Matrix

In [7]:
matrix = np.array([[1,2,3],
                    [4,5,6]])
print("matrix \n", matrix)

matrix 
 [[1 2 3]
 [4 5 6]]


Tensor

In [9]:
tensor = np.array([[[1,2], [3,4]],
                    [[5,6], [7,8]]])
print("tensor \n", tensor)

tensor 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
