### Addition

In [ ]:
import numpy as np

arr1 = np.array([1,2,3])
arr2 = np.array([4,7,10])
newarr = np.add(arr1, arr2)
print(newarr)

[ 5  9 13]


### Subtraction

In [ ]:
arr1 = np.array([1,2,13])
arr2 = np.array([4,7,10])
newarr = np.subtract(arr1, arr2)
print(newarr)

[-3 -5  3]


### Multiplication

In [9]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,7,1])
newarr = np.multiply(arr1, arr2)
print(newarr)

[ 4 14  3]


### Division

In [10]:
arr1 = np.array([5,14,13])
arr2 = np.array([4,7,10])
newarr = np.divide(arr1, arr2)
print(newarr)

[1.25 2.   1.3 ]


### Power

In [12]:
arr1 = np.array([10,20,30])
arr2 = np.array([2,3,2])
newarr = np.power(arr1, arr2)
print(newarr)

[ 100 8000  900]


###  Remainder

In [14]:
arr1 = np.array([11,20,30])
arr2 = np.array([2,3,2])
newarr = np.remainder(arr1, arr2)
print(newarr)

[1 2 0]


In [15]:
arr1 = np.array([11,20,30])
arr2 = np.array([2,3,2])
newarr = np.mod(arr1, arr2)
print(newarr)

[1 2 0]


###  Quotient and Mod

In [ ]:
arr1 = np.array([11,20,30])
arr2 = np.array([2,3,2])
newarr = np.divmod(arr1, arr2)
print(newarr)

# Output:
# (array([ 5,  6, 15]), array([1, 2, 0]))

# Explanation:
# For each element:
# 11 ÷ 2 = 5 quotient, remainder 1
# 20 ÷ 3 = 6 quotient, remainder 2
# 30 ÷ 2 = 15 quotient, remainder 0

(array([ 5,  6, 15]), array([1, 2, 0]))


### Absolute Values

In [ ]:
arr = np.array([-1, 2, -3, 1, 2, -2])
newarr = np.absolute(arr)   # Apply np.absolute to get absolute values (remove negative sign)
print(newarr)

[1 2 3 1 2 2]


In [19]:
arr = np.array([-1, 2, -3, 1, 2, -2])
newarr = np.abs(arr)
print(newarr)

[1 2 3 1 2 2]


# Summations
###  What is the difference between summation and addition? Addition is done between two arguments whereas summation happens over n elements.
### Addition :- [1,2,3] + [4,5,6] = [5,7,9] ,   Summation :- Sum of [1,2,3,4] = 10

In [21]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])
newarr = np.sum([arr1, arr2])
print(newarr)

12


## Summation Over an Axis
#### If you specify axis=1, NumPy will sum the numbers in each array.

In [22]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])
newarr = np.sum([arr1, arr2], axis=1)
print(newarr)

[6 6]


## Cummulative Sum
#### Cummulative sum means partially adding the elements in array.                                                                                       E.g. The partial sum of [1, 2, 3, 4] would be [1, 1+2, 1+2+3, 1+2+3+4] = [1, 3, 6, 10].
#### Perfom partial sum with the cumsum() function.

In [23]:
arr = np.array([1,2,3])
newarr = np.cumsum(arr)
print(newarr)

[1 3 6]


# Products

#### To find the product of the elements in an array, use the prod() function.  E.g. product of [1, 2, 3, 4]  =>  1 * 2 * 3 * 4 = 24

In [25]:
arr = np.array([1,2,3,4])
newarr = np.prod(arr)
print(newarr)

24


In [ ]:
#  Find the product of the elements of two arrays:

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])
x = np.prod([arr1, arr2])        # 1 * 2 * 3 * 4 * 5 * 6 * 7 * 8 = 40320
print(x) 


40320


## Product Over an Axis
#### If you specify axis=1, NumPy will return the product of each array.

In [ ]:

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])
newarr = np.prod([arr1, arr2], axis=1)
print(newarr)

#  Step-by-Step Product per Row
# First row:
# 1 * 2 * 3 * 4 = 24
# Second row:
# 5 * 6 * 7 * 8 = 1680



[  24 1680]


## Cummulative Product
#### Cummulative product means taking the product partially. E.g. The partial product of [1, 2, 3, 4] is [1, 1*2, 1*2*3, 1*2*3*4] = [1, 2, 6, 24]
#### Perfom partial sum with the cumprod() function.

In [29]:
arr = np.array([5,8,3,2])
newarr = np.cumprod(arr)
print(newarr)

[  5  40 120 240]


# Differences
### A discrete difference means subtracting two successive elements. E.g. for [1, 2, 3, 4], the discrete difference would be [2-1, 3-2, 4-3] = [1, 1, 1]
## To find the discrete difference, use the diff() function.

In [32]:
arr = np.array([3,4,8,11,16])
newarr = np.diff(arr)
print(newarr)

[1 4 3 5]


#### We can perform this operation repeatedly by giving parameter n.  E.g. for [1, 2, 3, 4], the discrete difference with n = 2 would be [2-1, 3-2, 4-3] = [1, 1, 1] , then, since n=2, we will do it once more, with the new result: [1-1, 1-1] = [0, 0]

In [35]:
arr = np.array([3,4,8,11,16])
newarr = np.diff(arr, n=2)
print(newarr)

[ 3 -1  2]
