NumPy provides trigonometric functions as ufuncs that:

Take input in radians.
Return the corresponding sine, cosine, or tangent values.

In [2]:
import numpy as np

# Find sine value of PI/2:

x = np.sin(np.pi/2)
print(x)

1.0


In [3]:
# Find sine values for all of the values in arr:  [np.pi/2, np.pi/3, np.pi/4, np.pi/5]

x = np.sin([[np.pi/2, np.pi/3, np.pi/4, np.pi/5]])
print(x)

[[1.         0.8660254  0.70710678 0.58778525]]


### Convert Degrees Into Radians

In [6]:
# Formula to convert degrees to radians:
# radians = degrees × (𝜋/180)

arr = np.array([90, 180, 45, 30])
x = np.deg2rad(arr)
print(x)

[1.57079633 3.14159265 0.78539816 0.52359878]


###  Radians to Degrees

In [7]:
arr = np.array([np.pi/2, np.pi, 1.5*np.pi, 2*np.pi])
x = np.rad2deg(arr)
print(x)

[ 90. 180. 270. 360.]


###  Finding Angles

In [ ]:
# Finding angles from values of sine, cos, tan. E.g. sin, cos and tan inverse (arcsin, arccos, arctan).
# NumPy provides ufuncs arcsin(), arccos() and arctan() that produce radian values for corresponding sin, cos and tan values given.

In [8]:
x = np.arcsin(1.0)
print(x)

1.5707963267948966


###  Angles of Each Value in Arrays

In [10]:
# Find the angle for all of the sine values in the array :- [1, -1, 0.1]

arr = np.array([1, -1, 0.1])
x = np.arcsin(arr)
print(x)

[ 1.57079633 -1.57079633  0.10016742]


###  Hypotenues

In [ ]:
# Finding hypotenues using pythagoras theorem in NumPy.
# NumPy provides the hypot() function that takes the base and perpendicular values and produces hypotenues based on pythagoras theorem.

In [ ]:
# Find the hypotenues for 4 base and 3 perpendicular:

base = 4
perp = 3
x = np.hypot(base, perp)   
print(x)

5.0
